apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: injection
  annotations:
    sidecar-injector-webhook.wallarm.injected/inject: "true"
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: dvwa
        image: "vulnerables/web-dvwa:latest"
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 80
