apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: injection
  annotations:
    sidecar-injector-webhook.wallarm.injected/inject: "true"
spec:
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80